web/web/vote/urls.py
from django.conf.urls import url

from . import views

app_name = 'vote'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^trends/$', views.trends, name='trends'),
    url(r'^vote/$', views.vote, name='vote'),
]

web/web/web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^vote/', include('vote.urls')),
    url(r'^admin/', admin.site.urls),
]

web/web/vote/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    total = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')

web/web/vote/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import Question
from django.db.models import Sum

# Create your views here.
def index(request):
    return HttpResponse("Hello, world. You're at the voting index.")

def vote(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'vote/index.html', context)

def trends(request):
    latest_question_list = Question.objects.order_by('-votes')
    total = Question.objects.aggregate(Sum('votes'))
    context = {
        'latest_question_list': latest_question_list,
        'total_votes': total
    }
    return render(request, 'vote/trends.html', context)

web/web/vote/templates/vote/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Voting App</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <br><br><br>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Voting App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vote:vote' %}">Vote <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vote:trends' %}">Trends</a>
          </li>
        </ul>
      </div>
    </nav>
    <main role="main" class="container">
      <div class="jumbotron">
        {% if latest_question_list %}
          <form action="{% url 'vote:vote' %}" method="post">
            {% for question in latest_question_list %}
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="{{ question.id }}" name="{{ question.id }}" value="{{ question.id }}">
                <label class="form-check-label" for="{{ question.id }}">{{ question.question_text }}</label>
              </div>
            {% endfor %}
          <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

web/web/vote/templates/vote/trends.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Voting App</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <br><br><br>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Voting App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'vote:vote' %}">Vote</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'vote:trends' %}">Trends <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="jumbotron">
        {% load mathfilters %}
        {% if latest_question_list %}
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Vote</th>
                  <th scope="col">Percentage</th>
                <tr>
              </thead>
              <tbody>
                {% for question in latest_question_list %}
                  <tr>
                  {% with numerator=question.votes denominator=total_votes.votes__sum %}
                    <td>{{ question.question_text }}</td>
                    <td>{{ question.votes }}</td>
                    <td>{{ numerator|div:denominator|mul:100  }}%</td>
                  {% endwith %}
                </tr>
                {% endfor %}
              </tbody>
            </table>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
      </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>